"""Create the submission-facing mechanism schematic.

The empirical/result figures are generated by the analysis scripts copied into
this package.  This script only draws the conceptual figure, so the figure is
fully reproducible and contains no AI-generated artwork.
"""

from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, Rectangle


ROOT = Path(__file__).resolve().parents[1]
# In the submission package, keep the conceptual figure with the manuscript;
# in the standalone public reproducibility tree, write it to that tree's
# outputs directory rather than modifying a sibling project directory.
OUT = (
    ROOT.parent / "manuscript" / "figures"
    if (ROOT.parent / "manuscript").exists()
    else ROOT / "outputs"
)
OUT.mkdir(parents=True, exist_ok=True)


def draw_stack(ax, x0, y0, width, height, n, color="#dbeafe", show_label=False):
    for i in range(n):
        y = y0 + i * height
        ax.add_patch(
            Rectangle(
                (x0, y), width, height * 0.92,
                facecolor=color, edgecolor="#1e3a8a", linewidth=1.2,
            )
        )
    if show_label:
        ax.text(x0 + width / 2, y0 - 0.16, f"{n} units", ha="center", va="top", fontsize=9)


def main():
    plt.rcParams.update({"font.size": 10, "font.family": "DejaVu Sans"})
    fig = plt.figure(figsize=(11.0, 5.0), constrained_layout=True)
    gs = fig.add_gridspec(1, 3, width_ratios=[1.0, 1.15, 1.25])
    ax1, ax2, ax3 = [fig.add_subplot(gs[0, i]) for i in range(3)]

    # (a) deterministic scaffold
    draw_stack(ax1, 0.18, 0.22, 0.48, 0.17, 4)
    ax1.add_patch(Rectangle((0.05, 0.12), 0.74, 0.08, facecolor="#e5e7eb", edgecolor="#4b5563"))
    ax1.add_patch(FancyArrowPatch((0.10, 0.94), (0.10, 0.70), arrowstyle="-|>", mutation_scale=14, linewidth=1.5, color="#111827"))
    ax1.text(0.10, 0.98, "g", ha="center", va="bottom", fontsize=11)
    ax1.add_patch(FancyArrowPatch((0.78, 0.55), (0.98, 0.55), arrowstyle="-|>", mutation_scale=14, linewidth=1.5, color="#b91c1c"))
    ax1.text(0.88, 0.61, "q", ha="center", color="#b91c1c", fontsize=11)
    ax1.text(0.43, 0.02, r"$q_{\rm slide}=\mu\rho bg+c b/h$", ha="center", fontsize=10)
    ax1.text(0.43, 1.07, "(a) pressure-driven limit states", ha="center", fontweight="bold")
    ax1.set_xlim(0, 1.0); ax1.set_ylim(0, 1.13); ax1.axis("off")

    # (b) geometry-equivalent cases and contact architecture
    # Use the same scalar geometry score in the drawing as in the text:
    # b/(2h)=0.225/(2*0.18)=0.625 and b/(4h)=0.45/(4*0.18)=0.625.
    draw_stack(ax2, 0.08, 0.22, 0.225, 0.18, 2, color="#dcfce7")
    draw_stack(ax2, 0.58, 0.22, 0.45, 0.18, 4, color="#fef3c7")
    ax2.add_patch(Rectangle((0.02, 0.12), 1.07, 0.08, facecolor="#e5e7eb", edgecolor="#4b5563"))
    ax2.text(0.1925, 0.99, r"$b/(Nh)=0.625$", ha="center", fontsize=9.5)
    ax2.text(0.805, 0.99, r"$b/(Nh)=0.625$", ha="center", fontsize=9.5)
    ax2.text(0.1925, 0.03, "parallel, N=2", ha="center", fontsize=9)
    ax2.text(0.805, 0.03, "perpendicular, N=4", ha="center", fontsize=9)
    ax2.annotate("same scalar\nthreshold", xy=(0.44, 0.80), xytext=(0.44, 0.93), ha="center",
                 va="center", arrowprops=dict(arrowstyle="<->", color="#374151"), fontsize=8.5)
    ax2.text(0.50, 1.07, "(b) scalar identifiability limit", ha="center", fontweight="bold", fontsize=9.5)
    ax2.set_xlim(0, 1.1); ax2.set_ylim(0, 1.13); ax2.axis("off")

    # (c) mechanism chain
    boxes = [
        (0.05, 0.70, 0.90, 0.18, "contact orientation\nand roughness"),
        (0.05, 0.41, 0.90, 0.18, "distribution of $\\mu_{\\rm eff}$\nand angle scatter"),
        (0.05, 0.12, 0.90, 0.18, "mixed sliding/toppling\nand gravity-dependent crossover"),
    ]
    for x, y, w, h, label in boxes:
        ax3.add_patch(Rectangle((x, y), w, h, facecolor="#f3f4f6", edgecolor="#111827", linewidth=1.1))
        ax3.text(x + w / 2, y + h / 2, label, ha="center", va="center", fontsize=10)
    # Place arrows in the actual gaps between boxes, rather than inside the
    # destination boxes, so the causal chain is visually unambiguous.
    for y0, y1 in ((0.69, 0.60), (0.40, 0.31)):
        ax3.add_patch(FancyArrowPatch((0.50, y0), (0.50, y1), arrowstyle="-|>", mutation_scale=13, linewidth=1.2, color="#374151"))
    ax3.text(0.50, 1.07, "(c) proposed contact-law mechanism", ha="center", fontweight="bold", fontsize=9.5)
    ax3.set_xlim(0, 1.0); ax3.set_ylim(0, 1.13); ax3.axis("off")

    fig.savefig(OUT / "fig1_mechanism_schematic.png", dpi=300)
    fig.savefig(OUT / "fig1_mechanism_schematic.svg")
    plt.close(fig)
    print(f"Wrote {OUT / 'fig1_mechanism_schematic.png'}")


if __name__ == "__main__":
    main()
